export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAILED = "USER_SEARCH_FAILED";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const USER_REPO_SEARCH_REQUEST = "USER_REPO_SEARCH_REQUEST";
export const USER_REPO_SEARCH_SUCCESS = "USER_REPO_SEARCH_SUCCESS";
export const USER_REPO_SEARCH_FAILED = "USER_REPO_SEARCH_FAILED";

export const SEARCH_USER_VALUE_CHANGE = "SEARCH_USER_VALUE_CHANGE";
export const SEARCH_USER_VALUE_CLEAR = "SEARCH_USER_VALUE_CLEAR";
